#!/bin/sh

export EDITOR=nvim

export NO_AT_BRIDGE=1

# Session
XDG_RUNTIME_DIR="$(mkrundir)"
export XDG_RUNTIME_DIR
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river

# Wayland
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# bemenu color theme
# https://github.com/catppuccin/bemenu
export BEMENU_OPTS='--fb "#24273a" --ff "#cad3f5" --nb "#24273a" --nf "#cad3f5" --tb "#24273a" --hb "#24273a" --tf "#ed8796" --hf "#eed49f" --af "#cad3f5" --ab "#24273a"'

# Run user services
superd &

exec dbus-run-session -- river
