#!/bin/sh

export EDITOR=nvim

export NO_AT_BRIDGE=1

# Session
export XDG_RUNTIME_DIR=$(mkrundir)
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river

# Wayland
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# Run user services
superd &

exec river
